development:
  adapter: mysql2
  encoding: utf8
  database: pin-stories
  username: root
  password: root
  host: localhost
  pool: 5
  timeout: 5000
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  database: pin-stories-test
  username: root
  password: root
  host: localhost
  pool: 5
  timeout: 5000
  
production:
  adapter: mysql2
  encoding: utf8
  database: pin-stories-production
  username: root
  password: root
  host: localhost
  pool: 5
  timeout: 5000
  reconnect: true